### ISSUE TITLE
Regarding license information for the examples

### ISSUE THREAD

**Issue by niki4810** [rupl/css3playground.com#3]
Hi Chris,

Firstly, thanks for sharing the flip transitions example via your [site](http://css3playground.com/flip-card.php).  The examples are really cool and css solution is elegant.

I looked around the files in the repo and did not find any license information for your examples. Could you please include/specify license policy for your examples? 

This is not really an issue, but though this would be the easiest way to contact you.

Thanks,
Nikhilesh

**Comment by rupl** [comment]
Hi, glad you found the code helpful! I've never really thought about it before, but I've decided that the examples are licensed under http://creativecommons.org/publicdomain/zero/1.0/ (public domain) - use for any purpose you desire without attribution :gift:

Thanks for pointing this out. I'll follow up with a PR to properly resolve the issue.
